name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # 리포지토리 전체를 루트 디렉터리에 체크아웃

      - uses: actions/setup-node@v4  # 프로젝트 루트에서 Node.js 설정
        with:
          node-version: 18
          cache-dependency-path: docs/package-lock.json
          cache: npm

      - name: Install dependencies
        run: npm ci
        working-directory: ./docs

      - name: Build website
        run: npm run build
        working-directory: ./docs

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
